{% set name = "relentless" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/relentless-{{ version }}.tar.gz
  sha256: 573afc26ea4cfcf68b235437638628635bdc5a147bac5d1f32866b839b042b7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.8
    - freud >=2
    - gsd
    - lammpsio >=0.4
    - networkx >=2.5
    - numpy
    - packaging
    - scipy

test:
  imports:
    - relentless
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mphowardlab/relentless
  summary: Computational materials design, with less code
  description: |
    relentless is a Python package for executing molecular simulations in larger
    computational workflows. The simulation protocol is specified as a
    reproducible, human-readable recipe that is run natively in popular engines
    such as LAMMPS and HOOMD-blue. relentless also has robust features for
    optimization with simulations, including independent and dependent variables
    with automatic differentiation, objective functions of simulations, and
    optimization methods.  All features are readily extensible through a clean
    hierarchy of abstract objects, enabling you to quickly use your own
    simulation code or optimization objective.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://relentless.readthedocs.io
  dev_url: https://github.com/mphowardlab/relentless

extra:
  recipe-maintainers:
    - mphoward
